// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHc2Wsjumw6AoXEedR7-I4fEuEb99EVfM',
    appId: '1:17348673605:web:01f8bcbf902b942d85a32c',
    messagingSenderId: '17348673605',
    projectId: 'flutterfirejesen',
    authDomain: 'flutterfirejesen.firebaseapp.com',
    storageBucket: 'flutterfirejesen.appspot.com',
    measurementId: 'G-1W2353RJSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbpgkpsgiO6cqKFlEYAu8YTPzJS0wIAg',
    appId: '1:17348673605:android:140008de7b6cd0f885a32c',
    messagingSenderId: '17348673605',
    projectId: 'flutterfirejesen',
    storageBucket: 'flutterfirejesen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZg3G5fwV-0BoglVfJOdOOVsxcr7r32Jk',
    appId: '1:17348673605:ios:02b6aebee424f2d085a32c',
    messagingSenderId: '17348673605',
    projectId: 'flutterfirejesen',
    storageBucket: 'flutterfirejesen.appspot.com',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZg3G5fwV-0BoglVfJOdOOVsxcr7r32Jk',
    appId: '1:17348673605:ios:02b6aebee424f2d085a32c',
    messagingSenderId: '17348673605',
    projectId: 'flutterfirejesen',
    storageBucket: 'flutterfirejesen.appspot.com',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHc2Wsjumw6AoXEedR7-I4fEuEb99EVfM',
    appId: '1:17348673605:web:480956c0a4124adb85a32c',
    messagingSenderId: '17348673605',
    projectId: 'flutterfirejesen',
    authDomain: 'flutterfirejesen.firebaseapp.com',
    storageBucket: 'flutterfirejesen.appspot.com',
    measurementId: 'G-KRKHPXBGBJ',
  );
}
