// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkB1ZADqD1D-0Ce246FrWsgfuLtGP3NDo',
    appId: '1:199949913122:web:17d056f9232b4d973f4e7b',
    messagingSenderId: '199949913122',
    projectId: 'notes-81706',
    authDomain: 'notes-81706.firebaseapp.com',
    storageBucket: 'notes-81706.appspot.com',
    measurementId: 'G-5T3KHGKKMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADkAJbYH4OnpmLkuc7t9dbAdH9LzHMshs',
    appId: '1:199949913122:android:c0fb4479191ecfdc3f4e7b',
    messagingSenderId: '199949913122',
    projectId: 'notes-81706',
    storageBucket: 'notes-81706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wGnf5-5J614sq9UwQWoi1ikAfIb_7zQ',
    appId: '1:199949913122:ios:4d7655b1eeea94c63f4e7b',
    messagingSenderId: '199949913122',
    projectId: 'notes-81706',
    storageBucket: 'notes-81706.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0wGnf5-5J614sq9UwQWoi1ikAfIb_7zQ',
    appId: '1:199949913122:ios:76f5bdf14ac209e33f4e7b',
    messagingSenderId: '199949913122',
    projectId: 'notes-81706',
    storageBucket: 'notes-81706.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
